server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${zhuanzhuan.datasource.driver-class-name}
      url: jdbc:mysql://${zhuanzhuan.datasource.host}:${zhuanzhuan.datasource.port}/${zhuanzhuan.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${zhuanzhuan.datasource.username}
      password: ${zhuanzhuan.datasource.password}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhuanzhuan.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    com:
      zhuanzhuan:
        mapper: debug
        service: info
        controller: info

zhuanzhuan:
  jwt:
    admin-secret-key: zhuanzhuan
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: zhuanzhuan-user
    user-ttl: 7200000
    user-token-name: token

  alioss:
    endpoint: ${zhuanzhuan.alioss.endpoint}
    region: ${zhuanzhuan.alioss.region}
    bucket-name: ${zhuanzhuan.alioss.bucket-name}
  virtual-wallet:
    scheme: ${zhuanzhuan.virtual-wallet.scheme}
    app-id: ${zhuanzhuan.virtual-wallet.app-id}
    callback-url: ${zhuanzhuan.virtual-wallet.callback-url}
    return-url: ${zhuanzhuan.virtual-wallet.return-url}
    sign-secret: ${zhuanzhuan.virtual-wallet.sign-secret}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: default
      paths-to-match: /**
      packages-to-scan: com.zhuanzhuan.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
