#数据库配置
zhuanzhuan:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: zhuanzhuan
    username: root
    password: 1218
  alioss:
    bucket-name: zhuanzhuancampus
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing

