#数据库配置
zhuanzhuan:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: zhuanzhuanCampus
    username: root
    password: 20041021
#3233233223
#fwefewfwfwefwesynnnnn
#操i福气哦i的钱钱钱钱钱钱我顶顶顶顶顶333333333333333333333333333333333333333333333333333333333
#测试一些

#osdosfs

#devepl