server:
  port: 8081

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${zhuanzhuan.datasource.driver-class-name}
      url: jdbc:mysql://${zhuanzhuan.datasource.host}:${zhuanzhuan.datasource.port}/${zhuanzhuan.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${zhuanzhuan.datasource.username}
      password: ${zhuanzhuan.datasource.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhuanzhuan.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      zhuanzhuan:
        mapper: debug
        service: info
        controller: info

zhuanzhuan:
  jwt:
    admin-secret-key: itcast
    admin-ttl: 7200000
    admin-token-name: token

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: default
      paths-to-match: /**
      packages-to-scan: com.zhuanzhuan.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
